---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggmatrix

<!-- badges: start -->
<!-- badges: end -->

Provide a geom able to rasterize matrices faster than `geom_raster()`.


## Installation

You can install the development version of ggmatrix from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("zeehio/ggmatrix")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(ggmatrix)

x_small <- c(3,5,7,9)
y_small <- c(100,200,300)
mat_small <- matrix(
  seq(from = 1, to = length(x_small)*length(y_small)),
  nrow = length(x_small),
  ncol = length(y_small)
)
dimnames(mat_small) <- list("x label" = x_small, "y label" = y_small)


ggplot() + geom_matrix_raster(matrix = mat_small)

```

